### ISSUE TITLE
Makale gonderimi (push ya da pull request)

### ISSUE THREAD

**Issue by cagriemer** [ubuntu-tr/ubuntu-tr.github.io#12]
Makaleleri dogrudan repoya mi gondermeliyiz yoksa pull request mi olusturmaliyiz?

**Comment by heartsmagic** [comment]
Merhaba Çağrı.

Bir ara toplansak da konuşsak aslında bunu. Bizim sistem ile doğrudan
repoya gitse ama önce görünmese diye falan konuşmuştuk. Buğra iki üç
gündür uğraşıyor sanırım sistem üzerinde, görmüşsündür haliyle sen de o
nedenle soruyorsundur bu soruyu. Hem son durumu öğrenmiş oluruz hem de
bir şeylere karar veririz. Müsait misin sen şu an?

18-04-2016 14:43 tarihinde Cagri Emer yazdı:

**Comment by cagriemer** [comment]
Ben su andan itibaren bir bucuk saat kadar musaitim. Eger size de uygunsa, toplanalim.

**Comment by neynefes** [comment]
Nerdeyiz :D

**Comment by heartsmagic** [comment]
18-04-2016 15:32 tarihinde neynefes yazdı:

> Nerdeyiz :D
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/ubuntu-tr/ubuntu-tr.github.io/issues/12#issuecomment-211359172

Lagaluga yapalım. Damlıyorum ben.

**Comment by bugra9** [comment]
Benim pull request oluşturmamdaki amaç api'nin direk buraya ulaşmasını engellemekti. Aslında bakınca fazlalık bir adım gibi duruyor. En güzeli bir oylama yapalım.

Makale forum kanalıyla onaylanınca direk kaydedilsin mi yoksa buraya pull request isteği mi yollasın?

**Comment by alquirel** [comment]
Ben forumdaki onayla düğmesini aslında bir durum çubuğu şeklinde kullanabiliriz diye düşünmüştüm. İnceleme başladı, imla tamamlandı, yayına hazır, yayınlandı falan gibisinden 3-4 basamaklı bir ilerleme bilgisi tutarız orada. Hani tüm düzenlemeleri orada yapabileceksek ara repoya gerek kalmayabilir, direkt kaydedebiliriz bence.

**Comment by bugra9** [comment]
Çok güzel olur.
