### ISSUE TITLE
Sistem çalışmıyor

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#2]
Yazıyı yazıyoruz, derlendi diye e posta geliyor ama çalışmıyor. Neden? :)

**Comment by bugra9** [comment]
Yazıda tarih alanına gelecek zamandan bir anı değil de geçmiş zamandan bir anı girersen yazın gözükecektir.

**Comment by neynefes** [comment]
Buğra hocam gıcıklığına yazdım :)

**Comment by bugra9** [comment]
Biliyorum, hata kaydı nasıl kapatılıyormuş denemek istedim. )
Kapatmışken de aynı sorunla karşılaşabilecek kişiler için not düştüm. :)
