### ISSUE TITLE
Slider'daki Mobil Görünüm

### ISSUE THREAD

**Issue by bugra9** [ubuntu-tr/ubuntu-tr.github.io#21]
Slider'daki resimler mobil görünümde çok küçük kalıyor, mobil görünüm için ayrı resim belirtme yeri eklensin.

**Comment by neynefes** [comment]
pixel verin bana ona göre ayar yapayım slider üzerinde

**Comment by bugra9** [comment]
Mobilde genişlik en fazla 768px oluyor. Slider görünecek ve üzerindeki yazılar okunacak şekilde her sliderdaki resim için bir de mobile göre ayrı resim hazırlanmalı.

**Comment by bugra9** [comment]
Önceden mobil için slider'ı kaldırmışız. Konunun açık olmasının anlamı kalmamış.
