### ISSUE TITLE
Ubuntu indirme linkleri ve makale gönderim sayfası

### ISSUE THREAD

**Issue by bugra9** [ubuntu-tr/ubuntu-tr.github.io#24]
Hem ubuntuya ait indirme linklerinin bulunduğu sayfaya gidecek hem de makale gönderme sayfasına gidecek ayrı ayrı 2 banner hazırlanıp ana sayfaya koyulmalı

**Comment by neynefes** [comment]
Pixel verip nereye koyulacağını söylerseniz ben hallederim.

**Comment by cagriemer** [comment]
Indirme baglantilari bir kutucuk seklinde "forumdan son yazilar" kutucugunun altina koyulabilir. En son kararli surum ve bir onceki surumun 32 ve 64 bit baglantilari verilir. Su anki durum icin bu 14.04 ve 16.04 baglantilari oluyor. Bir sonraki surumle birlikte 16.10 ve 16.04 olarak guncelleriz.

Makale gonderi bence ustteki navbar'da Ubuntu+1'in yanina koyarsak daha iyi olur. Sen de yaz falan gibi bir isim verebiliriz baglantiya.

**Comment by neynefes** [comment]
Sudo'ya indirme bağlantıları vermeye gerek var mı peki? Bence pek elzem değil gibi..

**Comment by cagriemer** [comment]
Dergiye baglanti diyorsan bence de gerek yok.

**Comment by neynefes** [comment]
Yok onu demiyorum. Sağ sütunda ubuntu indirme bağlantıları vermeyelim bence. O bağlantılar ubuntu-tr.net , ana sayfasında olsun.

**Comment by cagriemer** [comment]
Bence indirme baglantilari olsun portalda.

**Comment by neynefes** [comment]
Pekala nasıl isterseniz. Dediğim gibi genişlik verin ben hallederim gerisini.
