### ISSUE TITLE
Kategoriler

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#27]
Kategoriler bu şekilde mi kalacak? Ekleme çıkartma yapalım mı? Bu kadar kategori yeterli mi?

**Comment by bugra9** [comment]
Kimse katılmadığına göre yeterliymiş :)

**Comment by neynefes** [comment]
Çok mu kayıt açtık ne yaptık? İnsanlar takip edemiyor :D
