### ISSUE TITLE
Eski sayılar için kategori

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#30]
Dergiden çevirdiğimiz yazılar için bence ayrı kategori oluşturalım. Hem böylece yazıların eski olduğu hem de dergi formatında oldukları daha  anlaşılır olur. Sudo Nostalji gibi bir kategori oluşturabiliriz.

**Comment by bugra9** [comment]
Zaten "Sudo 61. Sayı" şeklinde etiketliyoruz. Ana sayfa da sağ sütunda sudoya ait tüm sayı etiketlerini listeletiriz ve isteyenler hızlıca okur.

**Comment by neynefes** [comment]
Banane ben istiyorum :D

**Comment by plazmax** [comment]
Bunları herkes görüyor mu yazışmaları yoksa sadece bizmi :D

**Comment by bugra9** [comment]
Kategori sayısının fazla olması responsive görünümde sorun yaratıyor. Olabildiğince kısa tutmaya çalışıyorum. Eklenebilecek o kadar önemli kategoriler var ki sudo eski sayılar için kategori açmaya gerçekten gerek var mı :)

Herkes görüyor :)

**Comment by neynefes** [comment]
İyi biraz daha goy goya bağlayım ben :D
