### ISSUE TITLE
Kramdown

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#31]
Bu editörün kullanımını türkçeleştirebilir miyiz?
http://kramdown.gettalong.org/quickref.html
http://kramdown.gettalong.org/syntax.html

**Comment by bugra9** [comment]
Açıkçası kramdown'ı hiç sevmedim. Github'ın sadece bunu desteklemesine de anlam veremiyorum. Acaba bu tarz şeyleri kapatıp düz markdown kullanabiliyor muyuz diye kafamda soru oluşmuyor değil.

Niye sevmediğime gelirsek:
Markdown'un çıkış amacı yazıyı oldukça basite indirgemek ve şekilli yazılmasının önüne geçmek değil mi. Zaten ondan dolayı toplasan 5-10 farklı kullanımı vardır. Ama kramdown gitmiş bunu almış, her şeyin yapılabileceği bir formata dönüştürmüş. Bununla da yetinmeyip normal markdown formatının özelliklerini ezmiş. Ben zaten her şeyi yapmak istesem gider word formatında ya da html formatında yazarım.

Hadi tüm bunları geçtim zaten bu proje fazla da destek alamamış. Githubın aklından ne geçiyor hiç bilmiyorum. https://github.com/gettalong/kramdown

**Comment by neynefes** [comment]
Peki kullanım konusunda ne diyoruz? Basitlik tamam da tasarımcı olarak özgürlük tanınması da fena olmaz hani. En basitinden küçük bir resmin yanından yazıyı akıtabilirsem bu çok güzel görünür.

**Comment by bugra9** [comment]
kramdown, markdown'un aksine block şeklinde çalışmak yerine inline şeklinde yorumluyor. Yani sen alt satıra geçsen de yan yana koyuyor çoğu şeyi ki resimde öyle. Sadece koyduğun resme boyut belirtirsen yazılar yanına gelecektir. Onu da aşağıdaki gibi yapabilirsin.

{: height="200px" width="200px"}

**Comment by neynefes** [comment]
Şimdi kramdown'da hemfikir miyiz? Kullanımını bir şekilde öğrenirim.

**Comment by bugra9** [comment]
kullanmaktan başka çaremiz yok, github bize zorla kullandırıyor :)

**Comment by cagriemer** [comment]
Derlemeyi nasilsa sunucumuzda yapiyoruz. Dolayisiyla Jekyll'in destekledigi herhangi bir markdown engine'i (kramdown disinda) secebiliriz. Burada sanirim onemli olan soru su, yazi gonderme formu kramdown destekliyor mu desteklemiyor mu? Karari buna gore verelim. Ben default olarak (Jekyll'in defaultu) kramdown'da kalma taraftariyim.

**Comment by bugra9** [comment]
O soruya ben de takılı kaldım. Bir araştırayım, javascript kramdown editor var mı yok mu diye.

**Comment by bugra9** [comment]
Bu konuya açıklık getirirsek;
- Sistemde kullandığımız kramdown ile ilgili bilgileri belgelendirme makalesine yazdım.
- Bir tane markdown editor alıp, kramdowna göre uyarladım.

**Comment by neynefes** [comment]
Ellere sağlık ne diyelim :)
