### ISSUE TITLE
Arama Çubuğu

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#33]
Arama Çubuğu eklenecek mi?

**Comment by bugra9** [comment]
Evet ama tamamen javascript ile çalışacak. Sitemap'i parse ettireceğim ki benzer yazılar da öyle çalışıyor. Tabi bu çok sonra eklenecek bir özellik.

**Comment by neynefes** [comment]
Arama çubuğu eklendiğinde menü ve arama simgesini sağ tarafa alabilir miyiz? Solda çok konforsuz bir kullanımı oluyor mobilde.

**Comment by bugra9** [comment]
Sağ tarafa da ayrı bir menü koymayı düşünüyordum :)

Biliyorsun mobil görünümde hep sağ sütunu göstermedik. Bu da kontrol kaybına neden oluyor. Şuan fazla makale olmadığı için hissedilmiyor ama ileride hissedilecektir. Bu sorunu çözmek için de sağa ayrı bir menü koymayı düşünmüştüm.

**Comment by neynefes** [comment]
Hımm.. Sağ tarafa 3 simge koyalım o zaman :) 6 inch ekrana sahip bir cihazdan bahsediyorum tabi. Ulaşılması zor oluyor.

**Comment by bugra9** [comment]
Tamam öyle yapalım o zaman :)

**Comment by neynefes** [comment]
https://codyhouse.co/gem/advanced-search-form/
Yine enfes bir öneri geliyor benden :)

**Comment by bugra9** [comment]
Biliyorsun, footer ve header'da forumdaki yapının dışına çıkmamaya çalışıyorum ki forumda arama kısmı header üzerinde bulunuyor. Yani arama çubuğu koyduğumuzda forumdaki yerinin aynısı ve aynı şekilde olmasını düşünüyorum.

**Comment by neynefes** [comment]
İyi o zman bütün yapıya entegre edelim :smile: Nasıl uygun görürseniz. Ben önereyim de :)

**Comment by bugra9** [comment]
Arama olayını ekledim. Kullanımını buraya not düşeyim.
- İlk arama hangi sayfa açık ise onun üzerinde yapılıyor. Yani kategori sayfası açıksa o kategorilere ait makalelerde, bir yazarın sayfası açık ise o yazara ait makalelerde arama yapıyor. Tüm iletilerde aramak istiyorsan ana sayfayı kullan :)
- Girilen kelimelerden herhangi biri makale içerisinde bulunursa sonuca yansıyor. Eğer bir kelimenin kesinlikle bulunmasını istiyorsan başına + işareti koyarak arat. (Örneğin: `oyun +mine`)
- Arama bulduğu her şeyi getiriyor. Mesela `mine` diye arama yaptığında `minecraft` veya `sistemine` kelimeleriyle eşleşebiliyor.
- Arama küçük/büyük harflere duyarsız.
- Aramada sıralama, puana göre değil eklenme zamanı baz alınarak yapılıyor.
- Arama, başlık, zaman, özet, yazar, kategori gibi alanlarda yapılıyor. İlerde etiketleri de ekleyeceğim. Asıl içerikte arama yapmıyor.
