### ISSUE TITLE
Sosyal medya butonları

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#36]
Yazıları paylaşmak için sosyal medya butonları koyalım.

**Comment by bugra9** [comment]
Aynen, olmazsa olmaz.

**Comment by betseg** [comment]
Font Awesome mı başka bir şey mi olacak?

**Comment by neynefes** [comment]
Bence gayet iyi bir tercih

**Comment by bugra9** [comment]
https://www.addthis.com/get/share
direk buradakini entegre ettim. Yalnız commit ederken belirtmeyi unutmuşum ve başka bir değişiklikle beraber geldi. c72ad03

**Comment by neynefes** [comment]
Görünmüyor mu ben mi bulamadım bu değişikliği?

**Comment by bugra9** [comment]
Reklam engelleyiciyi kapat :)

**Comment by neynefes** [comment]
ohoo :D

**Comment by bugra9** [comment]
Tamam da reklam engelleyicide sosyal butonları kaldırmasını seçmişsen hiçbir site kurtulamaz diye biliyorum.

**Comment by cagriemer** [comment]
Bizim bir addthis hesabimiz olacakti. Hesap detaylarini bulayim ben.

**Comment by bugra9** [comment]
Sharing Sidebar ile Mobile Sharing Toolbar'ı etkinleştirdim. Hem mobilde hem de masaüstünde güzel bir görüntü veriyor.

İkisinde de "Responsive Width" kısmını 900px olarak ayarladım.

**Comment by neynefes** [comment]
Neyse tasarım önerisini sonra veririm :)

**Comment by bugra9** [comment]
hazır yazılmış bir şeyi kullandığımız için sadece onların sundukları tasarımı kullanabilirsin.

İstersen https://www.addthis.com/get/share buraya üye olup tasarımları incele.

**Comment by cagriemer** [comment]
Hmm ben tabii bunu gormeden eski usul paylasim cubugunu iceren commit'i (#9057fdce) yolladim. Dedigin iki araci acayim eskisi yerine.

**Comment by bugra9** [comment]
Farketmez ben sadece not düşeyim dedim, bu şekilde de güzel görünüyor.

Bu arada yanlış hatırlamıyorsam aynı anda sadece 2 tanesini kullandırıyor. 3. için para istiyor. Yani dediğim iki aracı açacaksan eskisini kapatman lazım.

**Comment by cagriemer** [comment]
Ucunu de actim herhangi bir odeme uyarisi vermedi. Disqus yorum blogunun uzerindekini kaldirayim mi? Hem sagda cikmasi hem de yorumlarin orada cikmasi gereksiz mi?

**Comment by bugra9** [comment]
Bilemiyorum. 

Bir de o butonları sağ taraftan sol tarafa alsak nasıl olur? Kaydırma çubuğunun yanında olması çoğu kişiyi zorlar aksine makaleye yakın olması o düğmeleri daha anlamlı kılar diye düşünüyorum.

**Comment by cagriemer** [comment]
Sol tarafa aldim butonlari. Yorum blogunun ustundeki butonlari da kaldirdim.

**Comment by bugra9** [comment]
tamam, sağol.
