### ISSUE TITLE
Yazı Sayısı

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#37]
Her sayfa da mesela 10 yazı görünsün veya kullanıcıya da her sayfa da görüntülemek istediği yazı sayısını seçebilme şansı verelim?

**Comment by bugra9** [comment]
Bu biraz tartışmaya açık bir konu.

Sayfalama yapabileceğimiz gibi listenin sonuna devamını yükle gibi bir buton koyup, ona tıklanınca sonraki kayıtların gösterilmesini sağlayabiliriz. Böylece kullanıcının bir sayı seçme ihtiyacı olmaz.

**Comment by neynefes** [comment]
Evet bu da olabilir ama kesinlikle sayfa kısaltılmalı :)

**Comment by bugra9** [comment]
7737cf9 bu değişiklik ile çeşitli sayfalama yapıları eklendi. Ayarlardan istenilen seçilebilir.
