### ISSUE TITLE
Disqus

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#38]
Disqus neden yok?

**Comment by bugra9** [comment]
Vardı da yeni sisteme geçerken aktarmamışım demekki. Tekrar koyarım.

**Comment by neynefes** [comment]
Tamamdır. Hatırlatma olarak kalsın o vakit.

**Comment by cagriemer** [comment]
Ubuntu Turkiye adina bir hesap alip onu kullanalim.

**Comment by bugra9** [comment]
Tamam.

_config.yml dosyası içindeki disqus_id: bugra9 değişkenini ona göre değiştiriririz
