### ISSUE TITLE
Bu syntax güzel

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#40]
https://github.com/liamsymonds/simplygrey-jekyll/blob/master/css/syntax.css

**Comment by bugra9** [comment]
tamamdır eskisini bununla değiştiririm.

**Comment by neynefes** [comment]
Sanırım kod etiketleri kullanımında text diye girilen kısımlar arkaplanı beyaz olarak görünüyor. Diğer kodun ne olduğunu söylediğmiz veya hiçbir şey söylemediğimz kısımlarda sorun yok.

**Comment by neynefes** [comment]
Kod etiketlerinde python2-3 gibi bir kullanıma gitmeyin. Python yazın direk. Yorumlayacaktır.

Örnek

``````
    ```python
    deneme
    ```
``````

**Comment by neynefes** [comment]
Hiç renklendirme yapılmayan kod kısımları çok soluk görünüyor. Renk tonu biraz açılabilir mi?

**Comment by bugra9** [comment]
başka css dosyası bul :)

beyaz rengi değişken tanımı için kullanıyor, karışabilir

**Comment by neynefes** [comment]
Direk beyaz yapma canım :) Azıcık bej olsun.

**Comment by bugra9** [comment]
Açtım rengini. Rengi beğenmediysen değiştirsin.
