### ISSUE TITLE
Video

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#43]
Video ve ses dosyalarını harici bir bağlantı yerine sisteme entegre edilecek.

**Comment by neynefes** [comment]
Video için `<iframe>` tagını kullanarak mongodb makalesine videoyu yerleştirdim. Tam ekran oynatma sorunu var sadece. Bir de şu js eklentisini buldum işe yarar mı bilmiyorum.

[Fitvid JS](https://github.com/davatron5000/FitVids.js)

Birde MongoDB yazısındaki video silinmiş ben farklı bir video koydum deneme amaçlı onu da değiştirelim.

**Comment by bugra9** [comment]
Tam ekran olayını düzelttim. O js eklentisi anladığım kadarıyla video'nun genişlik/yükseklik oranına göre iframe'in genişlik/yükseklik oranını ayarlıyor.

**Comment by neynefes** [comment]
Tabi mobil uyum sıkıntısı da var :)

**Comment by bugra9** [comment]
o js eklentisi mobil için birebir :)

**Comment by bugra9** [comment]
Şimdi farkettim de koyduğun video 16:9 oranında. Eğer tüm videolar aynı şekilde ise video için responsive olayını css ile giderdim. Eğer farklıysa js ile çözeriz.

**Comment by bugra9** [comment]
https://www.youtube.com/embed/W-WihPoEbR4 şeklinde bağlantı kullanımında otomatik video dosyasına dönüşüyor. Sendeyaz sayfası ve siteye uygulandı, pdf çıktılarında ise normal bağlantı olarak gözükecektir.
