### ISSUE TITLE
Yazı Kutucukları

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#44]
Kutucukların sadece resim ve başlık kısımlarına tıklandığında ilgili makale açılıyor. Bu kutunun her yerine tıklanıldığında açılsın.

**Comment by bugra9** [comment]
Ben bunu sorun olarak görmüyorum, bilerek öyle yaptım :)
Eğer komple tıklanabilir olsaydı, siteyi telefonda açtığında kaydırma olayını zor yapardın, yanlışlıkla bir makalenin içerisine girerdin. Haksız mıyım?

**Comment by neynefes** [comment]
Girmek istediğimde de bu sefer her yeriyle etkileşemeyeceğim. Dokunmatik cihazlarda bence pek sorun teşkil etmeyecektir.

**Comment by bugra9** [comment]
O zaman bu konuyu tartışmaya dönüştürüyorum, yorumlara göre gerekeni yaparız.

**Comment by betseg** [comment]
Bence de böyle olsun :)

**Comment by neynefes** [comment]
Fazla kullanışsız oluyor ama bu şekilde.

**Comment by betseg** [comment]
Böyle dediğim her tarafına tıklanabilir olmasıydı :P

**Comment by neynefes** [comment]
Hehe :D

**Comment by bugra9** [comment]
o zaman o şekilde değiştirelim
