### ISSUE TITLE
En çok okunanlar

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#48]
Bu kısımda yazıların üzerinde kategori bilgisi eklenebilir mi?

**Comment by bugra9** [comment]
Zaten her kategorinin kendi çok okunanlar kısmı var. Sadece ana sayfadaki kısım için gerekli mi?

**Comment by neynefes** [comment]
Yazının hangi kategori de olduğu olsa fena olmazdı.

**Comment by bugra9** [comment]
Nereye yerleştireceksin ki, yer var mı?

**Comment by neynefes** [comment]
Boydan boya renk verilebilir satırlara. Ayrıca ben istekte bulunuyorum uğraştırma diyorsan kapat gitsin. Bende fikir çok :D

**Comment by bugra9** [comment]
etiketleri ve kod kısmını siyah/beyaza boyadın ve bu listeleme kısmının rengarenk mi olmasını istiyorsun :)

**Comment by neynefes** [comment]
Olayı çarpıtmayalım :)

**Comment by bugra9** [comment]
- Arkaplanın renklendirilmesine -1 oy kullanıyorum.
- Listeleri birbirinden ayıran ayıracın yani alt kenarlığın renklendirilmesine de tarafsız yani 0 oy kullanıyorum.

Oylama sonucuna göre değişiklik yaparız :)

**Comment by bugra9** [comment]
1 aydır ileti geçilmediği için kapatıyorum.
