### ISSUE TITLE
Slider önerisi

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#49]
https://codyhouse.co/gem/hero-slider/

Bu slider hoşuma gitti. Tam genişlik bir slider kullanmamız güzel görünecektir.

**Comment by betseg** [comment]
baya güzelmiş bence

**Comment by neynefes** [comment]
Hem bu tür bir slider kullandığımızda resim ayarlamakta kolay olur. Responsive olayı için de ayrı bir uğraşa girmemize gerek kalmaz.

**Comment by bugra9** [comment]
#51 buradaki olayı yapınca birden fazla slider'ı sisteme ekleyip sonra ayar dosyasından istediğimizi seçeriz.

**Comment by bugra9** [comment]
Ben olayı anlamadım. Bu tarz tam genişlik/yükseklikteki slider dergi yayınına uygun mu? Hani zihnimde uyarlamaya çalışıyorum ama bir türlü oturmuyor. Bizim header'in değişmeyeceğini göz önünde bulundurarak aklınızdaki düşünceyi açar mısınız :)

Bana göre bu yapı tek sayfalık siteler için uygun.

**Comment by neynefes** [comment]
Eğer çok uğraştırmayacaksa bir ekle ben ne demek istediğimi anlatayım. Yok bir ton iş olur dersen boşver.

**Comment by bugra9** [comment]
Tamam, akşama eklerim.

**Comment by neynefes** [comment]
Ellerin dert görmesin :)

**Comment by bugra9** [comment]
57d8329 değişikliği ile sisteme ekledim.

**Comment by bugra9** [comment]
Sisteme ekli ama içi dolu olmadığı için etkinleştirmedim. @neynefes içini doldurunca etkinleştirecektir :)
https://github.com/ubuntu-tr/ubuntu-tr.github.io/blob/master/extension/widget-block/heroSlider/_index.html buradan içini doldurursun.
