### ISSUE TITLE
İçindekiler Menüsü Öneri

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#50]
https://codyhouse.co/gem/reading-progress-indicator/

Bu menü şekli nasıl?

**Comment by bugra9** [comment]
Neresi için düşündün? Benim içindekiler tablosunun yerine mi?

**Comment by neynefes** [comment]
Aynen öyle. Hani çok anlamadım ama görüntüsü ve başlığın neresinde olduğunu gösteren ilerleme kısmıda gayet hoş görünüyor.

**Comment by bugra9** [comment]
Aynen çok hoş görünüyor ama gruplama olaylarını yapıyor mu merak ettim. Eğer gruplama yapmayıp tüm başlıkları basıyorsa örneğin python yazısında o liste ekrana sığmaz. Gerçi yapmıyorsa biz yaptırırız :)

**Comment by neynefes** [comment]
Fikir benden gerisi sizin maharetli parmaklarınızda :D

**Comment by bugra9** [comment]
tamam ileriki sürüme eklenecekler arasına alıyorum.

**Comment by heartsmagic** [comment]
Böyle şeyler olursa tadından yenmez :) 
Resmen uçuruyorsunuz portalımızı :)

**Comment by bugra9** [comment]
Buradaki ilk iletin hayırlı olsun :)

**Comment by heartsmagic** [comment]
Artık bakayım dedim :)

**Comment by neynefes** [comment]
Şükürler olsun :)

**Comment by bugra9** [comment]
Bunu uygulamayı denedim ama olacak gibi görünmüyor :) Adam direk kendi yapısı için yapmış, başkası kullanır mı diye hiç düşünmemiş.
