### ISSUE TITLE
Gitter kullanımı

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#53]
Abilerim bunu onaylayın :)

Mail gelmiş olması lazım birinize.

**Comment by heartsmagic** [comment]
Buyur bakalım :)

**Comment by neynefes** [comment]
Allah'ım inanamıyorum :D Çok mutluyum :D

**Comment by neynefes** [comment]
https://gitter.zendesk.com/hc/en-us/articles/200178951-Gitter-rooms

Buldum anlatımı. Herkesin izin vermesi gerekiyormuş sanırım.

**Comment by alquirel** [comment]
Ben de verdim

**Comment by cagriemer** [comment]
Sorun kimsenin girip oda olusturmamasiymis. Su haliyle cozuldugu icin kapatiyorum.

**Comment by neynefes** [comment]
Repo sahibi siz görünüyorsunuz. Ben veya Buğra abi ekleyemiyoruz.
