### ISSUE TITLE
Listelenen makalelerdeki resim boyutu

### ISSUE THREAD

**Issue by bugra9** [ubuntu-tr/ubuntu-tr.github.io#56]
Sanki listelenen makalelerdeki resimlerin hepsinin boyutları aynı olursa daha hoş bir görünüm olur. Ne diyorsunuz? Hatta orada özet kısmını da kaldırabiliriz.

Genelde tüm sitelerde bu şekilde.

**Comment by neynefes** [comment]
Hoş olabilir ama uyguluma zorluklarını da beraberinde getirir. Bazı makalelerde gerçekten resim sıkıntısı çekiyoruz.

**Comment by cagriemer** [comment]
En azindan listeledigimiz sayfada gozuken gorsellerin (muhtemelen yazilardaki ilk gorsel) hepsinin boyutunun ayni olmasi bence de daha guzel olur. Ayrica yazi ozetlerini de kaldirabiliriz. Sadece bir imaj ve yazinin basligi yeterli.

**Comment by neynefes** [comment]
Özet kısımlarını şu yüzden seviyorum; bazen hızlıca siteyi incelerken özet kısmını okuyup bir fikir sahibi oluyorum ve ona göre yazıyı okuyup okumama kararı alıyorum. Bence kalsın.

**Comment by bugra9** [comment]
Peki özet kısmını resmin üzerine alsam. Yani normal şartlarda gözükmeyecek ama imleci resmin üzerine getirince özet belirecek. Aynen aşağıdaki olay gibi.

http://semantic-ui.com/modules/dimmer.html#content-dimmer
+ düğmesine tıklayınca ne demek istediğimi anlarsınız. O olayın tıklama yapmadan sadece imlecin resim üzerine gelmesi durumu.

**Comment by neynefes** [comment]
İşte bana çözüm önerileriyle gel. Bayıldım :) Mobil için herhangi bir sakıncası olur mu?

**Comment by bugra9** [comment]
Mobilde bunu kullanamayız (3D touch özelliği olmayanlar için :)). Mobil için ya eski sistem özeti göstereceğiz ya da hiç göstermeyeceğiz. Orada yan yana listeleme olmadığı için gösterip göstermemenin görünüşe bir etkisi olmaz.

**Comment by neynefes** [comment]
O zamn mobilde gösterelim normal içinde senin önerini kullanalım.
