### ISSUE TITLE
Sütunlara arkaplan

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#58]
İki sütuna arkaplan koyup bir deneyebilir miyiz? Sol sütun beyaz sağ ise gri tonlarında olsun.

**Comment by bugra9** [comment]
Bir şeyler karaladım. Yerelde deneyip sonucunu yazarsın.

Aktif hale getirmek için,
_data/ubuntu-tr/settings.yml dosyasının içindeki
`style: "style1"`
satırını
`style: "style2,style1"`
şeklinde değiştir.

**Comment by neynefes** [comment]
Hata basıyor. Eklenti kısmında.. Çok mu geç bir deneme yaptım acaba :)

Ok. Çalıştı lakin hayallerimdeki etki oluşmamış vazgeçtim :)

**Comment by bugra9** [comment]
Hayallerini yaz, ona ulaşırız :)

**Comment by neynefes** [comment]
Oruç kafayla hayal kuramıyorum :) Bir ara bakınırız tekrar buna ;)
