### ISSUE TITLE
Mobilde üst çubuk tam çıkmıyor 

### ISSUE THREAD

**Issue by betseg** [ubuntu-tr/ubuntu-tr.github.io#59]

**Comment by bugra9** [comment]
Küçülttükçe sadece sonlardaki bağlantılar görünmüyor, herhangi bir kayma sorunu yok değil mi?

**Comment by betseg** [comment]
``` css
overflow: hidden;
```

gibi ama telefonun kenarı orası.

**Comment by neynefes** [comment]
Bende en son satır bir alta iniyor. Nexus 6

**Comment by betseg** [comment]
Chrome 50+CM13+S5

**Comment by bugra9** [comment]
Alta iniyorsa kesin sorun.

@betseg  sence nasıl olabilir? Örneğin ilk yaptığımda belirli bir genişliğin altına indikçe o elemanlara "display:none" veriyordum. Yazılar değişince yeniden ayarlamak gerekeceği için bu kullanımdan vazgeçtim. Gerçi yazılar kolay kolay değişmez, geri alınabilir.

**Comment by betseg** [comment]
@neynefes'in dediği gibi menü olabilir ama iki menü güzel durmaz. Şu anda var olan menünün altına ekleyip `<hr>` ile ayırsak?

**Comment by bugra9** [comment]
Olabilir ya da mobil için o ustteki bağlantıların sayısını az tuttururuz.

**Comment by betseg** [comment]
``` css
@media only screen and (max-device-width: 600px) {
    ul li:nth-child(n+4) {
        display:none;
    }
}
```

?
