### ISSUE TITLE
Kodlar taştığında kaydırma çubuğu mu çıksın yoksa alt satıra mı insin?

### ISSUE THREAD

**Issue by bugra9** [ubuntu-tr/ubuntu-tr.github.io#60]
Bazı editörler kaydırıyor bazıları da alt satıra indiriyor. Sizin için hangisi uygun?

Konusu geçen commit: 75e5f3d

**Comment by neynefes** [comment]
Kaydırma çubuğu çıksın.

**Comment by bugra9** [comment]
2-1 olduğu için kaydırma çubuğunu ekledim ve konum sorununu giderdim
