### ISSUE TITLE
Performans sorunu

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#61]
i7 3. nesil işlemci
GTX660m ekran kartı

Akn'ye çarpmış bir internet....

Firefox tarayıcımda ara sıra olmakla birlikte performans sorunları yaşamaktayım sayfa görüntülemede. Bilgisayarımı mı değiştirmeliyim?

**Comment by bugra9** [comment]
Resimleri görünür alana girdikten sonra yükletiyoruz. Resimlere boyut bilgisi girmediğimiz için her yeni resim yüklendiğinde tüm sitenin dizilimi yeniden hesaplanıyor ve bu da bir işlem gücü gerektiriyor. #56 da geçen konuyu çözdükten sonra resimlerin boyutu belli olduğu için her resim yüklemesinden sonra dizilimin yeniden hesaplanması gerekmeyecek ve kasma sorunu gidecek.

**Comment by bugra9** [comment]
Kendime not düşeyim, sliderdaki resimlere de boyut vermem lazım.

**Comment by bugra9** [comment]
cba1d9e : kod bakımından yapılacak her şeyi yaptım ve oldukça hızlandırdım. Geriye her makalenin resmi için küçük resim oluşturmak ve bu küçük resimleri listelemede kullanmak kalıyor. Onu da yapınca mükemmel bir hıza ulaşacaktır.

**Comment by bugra9** [comment]
Yapılan tüm iyileştirmelerin sonucunda aşağıdaki sonuçlara ulaştık.
https://gtmetrix.com üzerinden http://portaltest.ubuntu-tr.net araması sonucu;
- **PageSpeed Score:** A (92%)
- **YSlow Score:** B (89%)
- **Total Page Size:** 1.13 MB
- **Page Load Time:** 2.4 s

Şuan için hızın gayet yeterli olduğunu düşünüyorum. Daha fazla hızlandırmayı bir sonraki sürümde gerçekleştiririz.
