### ISSUE TITLE
Font Ayarlaması

### ISSUE THREAD

**Issue by bugra9** [ubuntu-tr/ubuntu-tr.github.io#62]
Yeni sisteme geçmeden önce font olarak "ubuntu" ayarlıydı ama @neynefes'in isteği üzerine font olarak "lato"'ya geçmiştik. Yeni sisteme geçince dışarıdan çağırılan tüm fontları silmiştim ve verdana gibi sistem fontlarını kullandığımızı düşünüyordum. Şansa bak ki yeni sistemde semantic-ui iskeletini kullanmaya başladık ve o da varsayılan olarak lato kullanıyormuş. Dolayısıyla eski-yeni sistem bir değişiklik olmamış.

Şimdi sistemde kullanılan fontları listelersek;
- Markdown alanı için "Helvetica Neue" kullanıyoruz.
- Icon olarak Font Awesome 4.3 kullanıyoruz ki `font-family: Icons;` şeklinde ulaşılabilir.
- Geri kalan her yerde "Lato" fontunu kullanıyoruz.
  
  Bu fontlar için ya da bu fontlar yerine başka font kullanmak istiyorsanız yorumlarınızı alayım.

**Comment by betseg** [comment]
Ubuntu +1

**Comment by bugra9** [comment]
komple mi ubuntu olsun yoksa yine markdown alanı ile diğerleri şeklinde ayrılsın mı?

**Comment by betseg** [comment]
ubuntu mono acayip süper bi font bence, her herde ubuntu olsun bence.

**Comment by cagriemer** [comment]
Kod bloklari icin ben de Ubuntu mono diyorum.

**Comment by bugra9** [comment]
Sistem geneli Ubuntu, kod bloklarının içine Ubuntu Mono uygulandı.

**Comment by neynefes** [comment]
Abi mobilde yazılar bir tık küçülsün olur mu? Görünüşü hemen etkileyecektir. Yazı stili gerçekten şahane.
