### ISSUE TITLE
Mobil görünüm için özet

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#63]
Mobil görünümde tasarım bozulmadığı için özetler kutucuklar içerisinde görüntülensin.

**Comment by bugra9** [comment]
Bir kere tıklarsan özet gösteriliyor, iki kere tıklarsan açılıyor. Olmuş mu veya uygun mu? :)

**Comment by neynefes** [comment]
Olmamış direk yazıyı açıyor. Bence kullanışsız olur bu şekilde.

Düzeltiyorum. Sudo tarafına yansımamış. Evet çalışıyor ama bana biraz kullanışsız gibi geldi.

**Comment by bugra9** [comment]
Tamam, o zaman direk aşağıya alayım.

**Comment by bugra9** [comment]
Aldım.
