### ISSUE TITLE
Gogs 

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#65]
Böyle bir servise denk geldim. Detayına çok vakıf olamadım. İnceleyip geri dönüş yaparsanız çok memnun olurum.

https://github.com/gogits/gogs

**Comment by bugra9** [comment]
Github iyidir. Bak geçen, bir kayda birden çok kişi atayamadığın için github ekibi pişmanlık duyup hemen birden fazla seçme özelliğini getirmişler :)
