### ISSUE TITLE
E-posta ve RSS

### ISSUE THREAD

**Issue by neynefes** [ubuntu-tr/ubuntu-tr.github.io#66]
Yeni yazılardan haberdar olmak için bir rss akışı veyahut e-posta ile bildirim almak istiyorum.

**Comment by bugra9** [comment]
Hep aklımda olan ve hep unuttuğum bir şeydi. Bir an önce eklemem lazım.

**Comment by neynefes** [comment]
Yine egom tavan yaptı :smile:

**Comment by bugra9** [comment]
Rss, e1029f8 düzenlemesiyle eklendi. Eğer her yeni makalede kayıt olanlara eposta gitmesi isteniyorsa FeedBurner servisinden üyelik alıp rss'i oraya bildirmemiz gerekiyor.
