### ISSUE TITLE
Eski yazıların tarihi aynı

### ISSUE THREAD

**Issue by onur** [ubuntu-tr/ubuntu-tr.github.io#69]
Merhaba eski yazıların hepsinin tarihi 19 Nisan olarak gözüküyor. Aslında yayımlandığı tarih olursa bence daha iyi olur.

**Comment by bugra9** [comment]
Merhaba, bildirim için teşekkürler. Aslında tüm makaleleri gözden geçirmeyi düşünüyordum ve bu aşamada tarihleri güncelleyecektim ama bir türlü gerçekleştiremedim. En iyisi şimdiden tarihleri güncellemek.

**Comment by bugra9** [comment]
Eski yazıların tarihlerini yayımlandığı tarih olarak düzelttim.

**Comment by neynefes** [comment]
@bugra9 kusura bakma yeni bakabildim. Ben bakmaya sen halletmişsin.

**Comment by onur** [comment]
Harika.

Bu arada bence yeni sudo harika olmuş ama hiç bir yerde duyurulmadığından kimsenin haberi yok gibi. Ben de yenilendiğini daha geçtiğimiz gün şans eseri farkettim navigasyonda sudo'ya tıklayınca.

**Comment by bugra9** [comment]
@neynefes, makalelerin tarihlerini, gününü de içeren şekilde bulamayacağımı düşündüğümden seni etiketlemiştim ama toplu indirme bağlantılarında hepsinin tam tarihinin yazdığını gördükten sonra kendim düzelttim. Tahmin ettiğimden daha kolay buldum.

@onur, yakında forumdan duyurusunu yapacağız.
