### ISSUE TITLE
Hiçbir sayfada <title> yok

### ISSUE THREAD

**Issue by onur** [ubuntu-tr/ubuntu-tr.github.io#70]

**Comment by bugra9** [comment]
v0.2 -> v0.3 geçişi sırasında alt yapıda köklü değişiklikler yapmıştık, o kısmı uyarlamayı unutmuşuz. Bu zamana kadar da böyle önemli bir şeyi hiç fark etmemişiz, bildirdiğin için teşekkürler.

Sorunu düzelttim.
