### ISSUE TITLE
Ana sayfadaki banner hiç bir işe yaramıyor

### ISSUE THREAD

**Issue by onur** [ubuntu-tr/ubuntu-tr.github.io#74]
Hem eski ubuntu sürümünün linki olmayan bir banner var hem de boş bir placeholder.

**Comment by neynefes** [comment]
Evet durumun farkındayız. İki farklı banner uygulamamız var. En kısa sürede ekleme ve düzeltmeler yapılacaktır.

**Comment by neynefes** [comment]
Slider bağlantıları ve resimleri düzenlendi.
