### ISSUE TITLE
Sende Yaz Makale Gönder Bölümü

### ISSUE THREAD

**Issue by siberoloji** [ubuntu-tr/ubuntu-tr.github.io#75]
Merhaba,
en son gönderdiğim Peek ile ilgili yazının hemen ardından "Driverless IPP " ile ilgili bir Ubuntu haberini de Sende Yaz kısmından makale gönderi kullanarak sisteme yüklemiştim. Makaleniz başarıyla gönderildi uyarısı da almıştım.
Onu bir ara kontrol eder misiniz? Ulaşmamış ise tekrar gönderebilirim.
Kolay gelsin.

**Comment by neynefes** [comment]
Yazı sisteme düşmemiş. Gönderilmiştir uyarısı gelmesine rağmen nerede hata oluştu acaba? @bugra9

**Comment by neynefes** [comment]
Bir dk. Abbas Dehmen adıyla mı gonderdiniz?

**Comment by siberoloji** [comment]
Tamam, tekrar yüklüyorum.

**Comment by neynefes** [comment]
Tekrar göndermeyin. Abbas Dehmen adıyla mı gonderdiniz?

**Comment by siberoloji** [comment]
Öyle mi yapmışım. Olabilir.
Sende yaz sayfasına girdiğimde Cache sayfada 1. adımda makalemi tekrar görebiliyorum ama ikinci adım form bilgileri Cache tutulmadığı için boş görünüyor.

**Comment by neynefes** [comment]
İletişim bilgileriniz aynı olduğu için yazıdaki bağlantıyı anlamaya çalışıyorduk. Ayrıca makalenin detaylandırılmasinida rica edecektik.

**Comment by siberoloji** [comment]
tamamdır, çalışayım...

**Comment by neynefes** [comment]
> E-posta listesinde yazıcıyı tanıtmak için 2 ayrı yöntem anlatılmış, bunlar dahil edilmeli. Bir de "IPP Everywhere, Apple AirPrint, Prints from iPhone and iPad, Prints from mobile devices" ifadesini barındıran yazıcılar için kullanılabildiği geçilmeli.

Kısaca şöyle dile de getirmiş olalım.

**Comment by siberoloji** [comment]
Yazıya son şeklini verdim. Sisteme yeni yazı olarak tekrar yüklüyorum. Önceki ile karışmasın.

**Comment by neynefes** [comment]
Çok teşekkür ederiz.. İlgi ve alakanız için.
